### ISSUE TITLE
Docker deployment and automatic testing checklist

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/probcomp-stack#35]
Adapted from axch's private checklist that got buried in a slack message a while back:

# Deployment process

- [ ] Pull the workshop-materials repo, since that's what's being (re-)deployed
  - Should this just be a submodule of probcomp-stack, or do we really want a script that pulls workshop-materials?
  - probcomp-stack is currently public; workshop-materials is currently private.
- [ ] Make sure the notebooks have been rebuilt by ./test/integration.sh in workshop-materials
- [ ] run ./scripts/prepare-content.sh in workshop-materials
- [ ] run ./release-container.sh in probcomp-stack (be sure to turn the
 cache off, and do this after the iventure package has been rebuilt)
- [ ] upload updated instructions to probcomp-website
- [ ] mirror to probcomp-1:/scratch/web/stack/probcomp-stack-full-0.1.zip

# Automatic testing of Docker container

- [ ] Check that the notebooks run in it (already done by probcomp-stack-crashes?)
- [ ] Check that the server comes up (already done by probcomp-stack-crashes?)
- [ ] Decide whether to strip the outputs of the notebook cells?
- [ ] Persistently serve the built html notebooks?
- [ ] Are we still maintaining the ubuntu1604 docker file in
 probcomp-stack?  If so, do we want to update it to consume the
 probcomp branding the way ubuntu1604-jupyter does? (see also: https://github.com/probcomp/probcomp-stack/issues/34)
- [ ] test/integration.sh
